project:
  type: website

website:
  title: "Coding The News"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css

editor: visual

